### ISSUE TITLE
Double definitions in search space

### ISSUE THREAD

**Issue by SamuelGabriel** [releaunifreiburg/WellTunedSimpleNets#4]
I get problems, that were solved when I replaced this if with an elif. I only understand the code on a very surface level, though. Not sure this is the right fix for these problems. It seems like 2 things happen: i) you assign to the same node twice (imputer) ii) the one-hot encoder is not supported for non-categorical features.
https://github.com/releaunifreiburg/WellTunedSimpleNets/blob/be5b3f3ccd3a5000b5108c19dc65c05357428fbc/utilities.py#L304

**Comment by SamuelGabriel** [comment]
after my fix, I get this problem, though:
`ValueError: Unknown hyperparameter for node SimpleImputer. Expected update hyperparameter to be in ['numerical_strategy'], but got categorical_strategy` for some datasets.

**Comment by ArlindKadra** [comment]
As discussed in person, the reason for the check is that otherwise trying to update the hyperparameter for the node when there is a lack of categorical or numerical hyperparameters would throw an error from the library.
