### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'predict'

### ISSUE THREAD

**Issue by DonIvanCorleone** [releaunifreiburg/WellTunedSimpleNets#7]
Hi there,

I stumbled across your project and paper and it seemed highly interesting. Unfortunately, I cannot successfully execute your project with my dataset. The following error occurs consistently 

```
Traceback (most recent call last):
  File "cocktails/main_experiment.py", line 399, in <module>
    train_predictions = fitted_pipeline.predict(X_train)
AttributeError: 'NoneType' object has no attribute 'predict'
```
I have checked, and double-checked the dataset but cannot find "the problem". All values are fine, properly scaled etc. etc.
The onlything thats maybe remarkable is: The dataside is a bit wide: 80000 x 650 bu nothing too out of bounds.

Do you have an idea what I should check?
Thanks for your support

Kind regards

**Comment by ArlindKadra** [comment]
Hey :),

Thanks for finding our work interesting. The first thing that comes into my mind, is that maybe the arguments might not be set ideally. For example, with a large dataset, `func_eval_time` needs to cover the time for a full function evaluation. https://github.com/releaunifreiburg/WellTunedSimpleNets/blob/494c978958d1c25e347e0f744c6a26a483734a41/cocktails/main_experiment.py#L61-L65 

I would suggest running for one epoch initially and not for 105, to see if the problem persists and then to adjust accordingly.https://github.com/releaunifreiburg/WellTunedSimpleNets/blob/494c978958d1c25e347e0f744c6a26a483734a41/cocktails/main_experiment.py#L66-L70

**Comment by ArlindKadra** [comment]
I will consider the issue resolved, if it still does not work, you can reopen it and  we can discuss it further :).

**Comment by DonIvanCorleone** [comment]
Sorry for the delayed response.

I tested you proposal with a highly reduced dataset = 7500 samples and a much longer func_eval_time = 86400 / epoch = 1. This setup achieved a result within ~ 45 minutes.
The moment I increased the dataset to 15000 samples  with same func_eval_time and epoch it fails again. 
By the way: I increased the number of workers to 8.

Any further suggestions? Any help highly appreciated :)

**Comment by DonIvanCorleone** [comment]
HI @ArlindKadra, by any chance some additional ideas?

**Comment by ArlindKadra** [comment]
Hey @DonIvanCorleone,

We do have an experimental branch that you could try out, it is `reg_cocktails-pytorch_embedding`. Theoretically, it should perform better in your case if there are multiple features and possibly some of them are categorical with a high dimensionality.

**Comment by DonIvanCorleone** [comment]
Hey @ArlindKadra,

thanks for your support. I tried yesterday and today to get your new approach running but at the moment something broke "entirely".

I am trying to dockerize the entire project and integrated all the required steps from this repository and the image seems to be properly setup but unfortunately in the very end I always receive the following new error after starting the process:

`[ERROR] [2022-10-28 10:30:17,276:Client-AutoPyTorch:734d2973-56ab-11ed-815f-0242ac110002:1] get_smac_object() got an unexpected keyword argument 'initial_configurations'`

Its unclear to me, whats happening and more specifically Why? :)  
It seems to me, that the setup of autoPyTorch and this repository is more complicated than expected and I don`t want to steal more support time from you. If you ever find the time to create a wokring dockerized version of your solution it would be awesome, but at the moment I don't see whats not working properly.

Many thanks again
Cheers

**Comment by DonIvanCorleone** [comment]
For the sake of completion these are the installed modules

Package                 Version
----------------------- -----------
absl-py                 1.3.0
autoPyTorch             0.2
cachetools              5.2.0
catboost                1.1
certifi                 2022.9.24
charset-normalizer      2.1.1
click                   8.1.3
cloudpickle             2.2.0
ConfigSpace             0.6.0
contourpy               1.0.5
cycler                  0.11.0
Cython                  0.29.32
dask                    2022.10.0
distributed             2022.10.0
emcee                   3.1.3
flaky                   3.7.0
fonttools               4.38.0
fsspec                  2022.10.0
google-auth             2.13.0
google-auth-oauthlib    0.4.6
graphviz                0.20.1
grpcio                  1.50.0
HeapDict                1.0.1
idna                    3.4
imageio                 2.22.2
imgaug                  0.4.0
importlib-metadata      5.0.0
Jinja2                  3.1.2
joblib                  1.2.0
kiwisolver              1.4.4
liac-arff               2.5.0
lightgbm                3.3.3
locket                  1.0.0
lockfile                0.12.2
Markdown                3.4.1
MarkupSafe              2.1.1
matplotlib              3.6.1
minio                   7.1.12
msgpack                 1.0.4
networkx                2.8.7
numpy                   1.23.4
oauthlib                3.2.2
opencv-python           4.6.0.66
openml                  0.12.2
packaging               21.3
pandas                  1.5.1
partd                   1.3.0
Pillow                  9.2.0
pip                     22.2.2
plotly                  5.11.0
protobuf                3.19.6
psutil                  5.9.3
pyarrow                 10.0.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pynisher                0.6.4
pyparsing               3.0.9
pyrfr                   0.8.3
python-dateutil         2.8.2
pytz                    2022.5
PyWavelets              1.4.1
PyYAML                  6.0
regex                   2022.9.13
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-image            0.19.3
scikit-learn            0.24.2
scipy                   1.9.3
setuptools              63.4.1
Shapely                 1.8.5.post1
six                     1.16.0
smac                    1.4.0
sortedcontainers        2.4.0
tabulate                0.9.0
tblib                   1.7.0
tenacity                8.1.0
tensorboard             2.10.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
threadpoolctl           3.1.0
tifffile                2022.10.10
toolz                   0.12.0
torch                   1.12.1
torchvision             0.13.1
tornado                 6.1
typing_extensions       4.4.0
urllib3                 1.26.12
Werkzeug                2.2.2
wheel                   0.37.1
xmltodict               0.13.0
zict                    2.2.0
zipp                    3.10.0
